sudo: required
dist: trusty

env:
  global:
    - PYTHONASYNCIODEBUG=1
    - SERIAL_REQUIRED=1

matrix:
  include:
    - language: python
      python:
        - '3.5'
        - '3.6'
      before_script:
        - pip install pyserial   # In Travis, plain pip always refers to the selected Python version. Nice.
        - cd python
      script:
        - ./popcop_test.py -vv
