sudo: required
dist: trusty

env:
  - PYTHONASYNCIODEBUG=1

matrix:
  include:
    - language: python
      python: 3.5
      before_script:
        - sudo pip install serial   # In Travis, plain pip always refers to the selected Python version. Nice.
        - cd python
      script:
        - ./popcop_test.py

