sudo: required
dist: trusty

env:
  global:
    - PYTHONASYNCIODEBUG=1      # https://docs.python.org/3/using/cmdline.html#envvar-PYTHONASYNCIODEBUG
    - SERIAL_REQUIRED=1         # Fail test unless pyserial is available

matrix:
  include:
    - language: python
      python: 3.5
      before_script:
        - pip install pyserial  # In Travis, plain pip always refers to the selected Python version. Nice.
        - cd python
      script:
        - ./popcop_test.py -vv

    - language: python
      python: 3.6
      before_script:
        - pip install pyserial
        - cd python
      script:
        - ./popcop_test.py -vv

    - language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      script:
        - CC=gcc-7 && CXX=g++-7 && cd c++/test/ && cmake . && make
        - ./popcop_test

    - language: cpp
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      script:
        - CC=clang-5.0 && CXX=clang++-5.0 && cd c++/test/ && cmake CMAKE_CXX_FLAGS='-stdlib=libc++' . && make
        - ./popcop_test
